#!/usr/bin/env bash
FOLDER=$1
#echo $FOLDER
#echo $PATH_TO_FILE
echo ++++++++++++++++++++++++++++++ >> ~/FS_Start.txt
echo $FOLDER >> ~/FS_Start.txt
echo starting time >> ~/FS_Start.txt
echo `date` >> ~/FS_Start.txt
echo ++++++++++++++++++++++++++++++ >> ~/FS_Start.txt

sleep 5
recon-all -subjid $FOLDER -all
#echo $FOLDER

echo ++++++++++++++++++++++++++++++ >> ~/FS_End.txt
echo $FOLDER >> ~/FS_End.txt
echo completion time >> ~/FS_End.txt
echo `date` >> ~/FS_End.txt
echo ++++++++++++++++++++++++++++++ >> ~/FS_End.txt