#!/bin/bash
#++++++++++++++++++++++++++ Script begins here ++++++++++++++++++++++++++
if [ "$1" == "-h" ] || [ "$1" == "-help" ] || [ "$1" == "--help" ]; then
    	########## HELP begins here ##########
    	echo
    	echo ""
    	echo " \$ `basename $0` <>"
    	echo
    	########### HELP ends here ###########
elif [ "$1" == "edit" ]; then
    	vim $0
else
    	if [ -z $1 ]; then
            	$0 --help
    	else
        	smoothing=$1
        	fsgd_file=$2
        	var1=$3
            	########## BODY begins here ##########
        	echo " + Preprocessing left hemisphere"
        	mris_preproc --fsgd "$fsgd_file" --target fsaverage --hemi lh --meas thickness --out lh._"$var1".thickness.00.mgh
        	echo " + Preprocessing right hemisphere"
        	mris_preproc --fsgd "$fsgd_file" --target fsaverage --hemi rh --meas thickness --out rh._"$var1".thickness.00.mgh
        	echo " + Smoothing left hemisphere"
        	mri_surf2surf --hemi lh --s fsaverage --sval lh._"$var1".thickness.00.mgh --fwhm "$smoothing" --cortex --tval lh._"$var1".thickness."$smoothing"B.mgh
        	echo " + Smoothing right hemisphere"
        	mri_surf2surf --hemi rh --s fsaverage --sval rh._"$var1".thickness.00.mgh --fwhm "$smoothing" --cortex --tval rh._"$var1".thickness."$smoothing"B.mgh
        	echo "+ GLM analysis left hemisphere"
        	mri_glmfit --y lh._"$var1".thickness."$smoothing"B.mgh --fsgd "$fsgd_file" dods --C group2.diff.mtx --surf fsaverage lh --cortex --glmdir lh."$var1"_thickness"$smoothing".glmdir
        	echo "+ GLM analysis right hemisphere"
        	mri_glmfit --y rh._"$var1".thickness."$smoothing"B.mgh --fsgd "$fsgd_file" dods --C group2.diff.mtx --surf fsaverage rh --cortex --glmdir rh."$var1"_thickness"$smoothing".glmdir

            	########### BODY ends here ###########

    	fi
fi
#+++++++++++++++++++++++++++ Script ends here +++++++++++++++++++++++++++